apiVersion: apps/v1
kind: Deployment
metadata:
  name: language-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: language-operator
  template:
    metadata:
      labels:
        name: language-operator
    spec:
      serviceAccountName: language-operator
      containers:
        - name: language-operator
          # Replace this with the built image name
          image: quay.io/example/language-operator:v0.0.1
          command:
          - language-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "language-operator"
